-- Seed MCQ Questions for Full-Stack Interview System
-- 30 Questions per Experience Level (Fresher, Junior, Senior)
-- Categories: HTML/CSS, JavaScript, React, Node.js, APIs, Databases, System Design, Security, Performance

-- =====================================================
-- FRESHER LEVEL QUESTIONS (30)
-- =====================================================

-- HTML/CSS Questions (5)
INSERT INTO interview_mcq_questions (category, experience_level, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty_score, tags) VALUES

('html_css', 'fresher', 'What does the HTML <article> tag represent?',
  'A standalone piece of content that could be distributed independently',
  'A section that contains navigation links',
  'A generic container for grouping elements',
  'The main content of the page',
  'a',
  'The <article> element represents a self-contained composition that could theoretically be distributed independently, like a blog post or news article.',
  3, ARRAY['html', 'semantic-html', 'basics']),

('html_css', 'fresher', 'Which CSS property is used to change the text color of an element?',
  'text-color',
  'font-color',
  'color',
  'text-style',
  'c',
  'The "color" property in CSS is used to set the foreground color (text color) of an element.',
  2, ARRAY['css', 'styling', 'basics']),

('html_css', 'fresher', 'What is the correct HTML for creating a hyperlink?',
  '<a url="https://example.com">Link</a>',
  '<link href="https://example.com">Link</link>',
  '<a href="https://example.com">Link</a>',
  '<hyperlink>https://example.com</hyperlink>',
  'c',
  'The <a> tag with href attribute is used to create hyperlinks in HTML.',
  2, ARRAY['html', 'links', 'basics']),

('html_css', 'fresher', 'Which CSS display property is used to make an element invisible but still take up space?',
  'display: none',
  'visibility: hidden',
  'opacity: 0',
  'hidden: true',
  'b',
  'visibility: hidden hides the element but maintains its space. display: none removes it from the layout flow, and opacity: 0 makes it transparent but clickable.',
  4, ARRAY['css', 'visibility', 'layout']),

('html_css', 'fresher', 'What is the purpose of the alt attribute in an <img> tag?',
  'To specify the image size',
  'To provide alternative text if image cannot be displayed',
  'To add a caption to the image',
  'To make the image responsive',
  'b',
  'The alt attribute provides alternative text for images, crucial for accessibility and displayed when images fail to load.',
  3, ARRAY['html', 'accessibility', 'images']),

-- JavaScript Questions (8)
('javascript', 'fresher', 'What is the correct way to declare a variable in JavaScript that cannot be reassigned?',
  'var myVar = 10',
  'let myVar = 10',
  'const myVar = 10',
  'variable myVar = 10',
  'c',
  'The "const" keyword declares a block-scoped variable that cannot be reassigned. However, if the value is an object or array, its properties/elements can still be modified.',
  3, ARRAY['javascript', 'variables', 'const']),

('javascript', 'fresher', 'Which method is used to add an element to the end of an array?',
  'array.add()',
  'array.push()',
  'array.append()',
  'array.insert()',
  'b',
  'The push() method adds one or more elements to the end of an array and returns the new length.',
  2, ARRAY['javascript', 'arrays', 'methods']),

('javascript', 'fresher', 'What does the typeof operator return for null?',
  '"null"',
  '"undefined"',
  '"object"',
  '"number"',
  'c',
  'This is a well-known JavaScript quirk. typeof null returns "object", which is considered a bug in JavaScript but has been kept for backward compatibility.',
  5, ARRAY['javascript', 'types', 'quirks']),

('javascript', 'fresher', 'What is the output of: console.log(2 + "2")?',
  '4',
  '"22"',
  'NaN',
  'Error',
  'b',
  'JavaScript performs type coercion. When adding a number and string, the number is converted to string, resulting in string concatenation: "22".',
  4, ARRAY['javascript', 'type-coercion', 'operators']),

('javascript', 'fresher', 'Which function is used to parse a string to an integer?',
  'Integer.parse()',
  'parseInt()',
  'parseInteger()',
  'toInt()',
  'b',
  'parseInt() is a global JavaScript function that parses a string and returns an integer. You can optionally specify the radix (base).',
  3, ARRAY['javascript', 'parsing', 'functions']),

('javascript', 'fresher', 'What does the "===" operator check for?',
  'Value equality only',
  'Type equality only',
  'Both value and type equality',
  'Reference equality only',
  'c',
  'The strict equality operator (===) checks for both value AND type equality, unlike == which performs type coercion.',
  3, ARRAY['javascript', 'operators', 'equality']),

('javascript', 'fresher', 'What is the purpose of the addEventListener() method?',
  'To create a new HTML element',
  'To attach an event handler to an element',
  'To remove an element from the DOM',
  'To modify element styles',
  'b',
  'addEventListener() registers an event listener on an element, allowing you to execute code when specific events occur (like clicks, key presses, etc.).',
  3, ARRAY['javascript', 'events', 'dom']),

('javascript', 'fresher', 'What does JSON stand for?',
  'JavaScript Object Notation',
  'Java Standard Object Notation',
  'JavaScript Oriented Network',
  'Java Serialized Object Notation',
  'a',
  'JSON stands for JavaScript Object Notation. It is a lightweight data interchange format that is easy for humans to read and write.',
  2, ARRAY['javascript', 'json', 'data']),

-- React Questions (6)
('react', 'fresher', 'What is the purpose of useState in React?',
  'To fetch data from an API',
  'To add state to functional components',
  'To handle routing',
  'To create context',
  'b',
  'useState is a React Hook that lets you add state to functional components. It returns a state value and a function to update it.',
  3, ARRAY['react', 'hooks', 'state']),

('react', 'fresher', 'What is JSX?',
  'A JavaScript library',
  'A syntax extension for JavaScript',
  'A type of CSS',
  'A database query language',
  'b',
  'JSX (JavaScript XML) is a syntax extension for JavaScript that allows you to write HTML-like code in JavaScript files. It gets compiled to React.createElement() calls.',
  3, ARRAY['react', 'jsx', 'fundamentals']),

('react', 'fresher', 'What does the "key" prop do in React lists?',
  'Encrypts the data',
  'Helps React identify which items have changed',
  'Styles the elements',
  'Validates the list items',
  'b',
  'Keys help React identify which items in a list have changed, been added, or removed. This optimizes rendering performance.',
  4, ARRAY['react', 'keys', 'lists']),

('react', 'fresher', 'Which method is called when a React component is first created?',
  'componentWillMount',
  'componentDidUpdate',
  'componentDidMount',
  'render',
  'c',
  'componentDidMount is called after a component is mounted (inserted into the DOM tree). In functional components, this is typically handled with useEffect.',
  4, ARRAY['react', 'lifecycle', 'mounting']),

('react', 'fresher', 'What is the virtual DOM in React?',
  'A copy of the actual DOM kept in memory',
  'A cloud-based DOM',
  'A testing environment',
  'A type of database',
  'a',
  'The virtual DOM is a lightweight copy of the actual DOM kept in memory. React uses it to calculate the minimal changes needed before updating the real DOM.',
  4, ARRAY['react', 'virtual-dom', 'concepts']),

('react', 'fresher', 'How do you pass data from a parent component to a child component in React?',
  'Using state',
  'Using props',
  'Using context only',
  'Using refs',
  'b',
  'Props (properties) are used to pass data from parent to child components in React. They are read-only in the child component.',
  2, ARRAY['react', 'props', 'data-flow']),

-- Node.js Questions (4)
('nodejs', 'fresher', 'What is Node.js?',
  'A JavaScript framework',
  'A JavaScript runtime built on Chrome''s V8 engine',
  'A database management system',
  'A CSS preprocessor',
  'b',
  'Node.js is a JavaScript runtime environment that allows you to run JavaScript on the server side, built on Chrome''s V8 JavaScript engine.',
  2, ARRAY['nodejs', 'fundamentals', 'basics']),

('nodejs', 'fresher', 'What is npm?',
  'Node Package Manager',
  'New Programming Method',
  'Node Programming Module',
  'Network Package Manager',
  'a',
  'npm is the Node Package Manager, the default package manager for Node.js. It helps manage project dependencies and packages.',
  2, ARRAY['nodejs', 'npm', 'packages']),

('nodejs', 'fresher', 'Which file contains all npm package dependencies?',
  'dependencies.json',
  'package.json',
  'npm.json',
  'node.json',
  'b',
  'package.json is the manifest file for Node.js projects, containing metadata about the project and its dependencies.',
  2, ARRAY['nodejs', 'package-json', 'dependencies']),

('nodejs', 'fresher', 'What command is used to install a package using npm?',
  'npm get package-name',
  'npm add package-name',
  'npm install package-name',
  'npm fetch package-name',
  'c',
  'npm install (or npm i) is the command to install packages. You can add --save to save it to dependencies in package.json (though this is now default).',
  2, ARRAY['nodejs', 'npm', 'commands']),

-- APIs Questions (3)
('apis', 'fresher', 'What does REST stand for in RESTful APIs?',
  'Representational State Transfer',
  'Remote Execution and State Transfer',
  'Rapid Execution State Transfer',
  'Real-time Execution State Transfer',
  'a',
  'REST stands for Representational State Transfer. It is an architectural style for designing networked applications using HTTP.',
  3, ARRAY['apis', 'rest', 'fundamentals']),

('apis', 'fresher', 'Which HTTP method is used to retrieve data from a server?',
  'POST',
  'GET',
  'PUT',
  'DELETE',
  'b',
  'GET is the HTTP method used to request data from a specified resource. It should only retrieve data and not modify it.',
  2, ARRAY['apis', 'http', 'methods']),

('apis', 'fresher', 'What is the purpose of the HTTP status code 404?',
  'OK - Request successful',
  'Unauthorized',
  'Not Found',
  'Internal Server Error',
  'c',
  '404 Not Found indicates that the server cannot find the requested resource. This is one of the most common HTTP error codes.',
  3, ARRAY['apis', 'http', 'status-codes']),

-- Databases Questions (2)
('databases', 'fresher', 'What does SQL stand for?',
  'Structured Query Language',
  'Simple Query Language',
  'Standard Query Language',
  'Systematic Query Language',
  'a',
  'SQL stands for Structured Query Language. It is used to communicate with and manipulate relational databases.',
  2, ARRAY['databases', 'sql', 'basics']),

('databases', 'fresher', 'Which SQL command is used to retrieve data from a database?',
  'GET',
  'FETCH',
  'SELECT',
  'RETRIEVE',
  'c',
  'SELECT is the SQL command used to retrieve data from one or more tables in a database.',
  2, ARRAY['databases', 'sql', 'queries']),

-- Git/Version Control (2)
('system_design', 'fresher', 'What is Git?',
  'A JavaScript framework',
  'A version control system',
  'A database',
  'A CSS preprocessor',
  'b',
  'Git is a distributed version control system used to track changes in source code during software development.',
  2, ARRAY['git', 'version-control', 'basics']);

-- =====================================================
-- JUNIOR LEVEL QUESTIONS (30)
-- =====================================================

INSERT INTO interview_mcq_questions (category, experience_level, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty_score, tags) VALUES

-- JavaScript Advanced (8)
('javascript', 'junior', 'What is a closure in JavaScript?',
  'A function inside another function',
  'A function that has access to variables in its outer scope even after the outer function has returned',
  'A way to close browser windows',
  'A method to encrypt data',
  'b',
  'A closure is a function that retains access to its lexical scope even when the function is executed outside that scope.',
  6, ARRAY['javascript', 'closures', 'advanced']),

('javascript', 'junior', 'What is the difference between let and var?',
  'let is block-scoped, var is function-scoped',
  'let is function-scoped, var is block-scoped',
  'They are the same',
  'let cannot be reassigned',
  'a',
  'let is block-scoped (only accessible within the block it was declared), while var is function-scoped (accessible throughout the function).',
  5, ARRAY['javascript', 'scope', 'variables']),

('javascript', 'junior', 'What does the spread operator (...) do?',
  'Divides arrays',
  'Expands iterables into individual elements',
  'Multiplies numbers',
  'Removes duplicates',
  'b',
  'The spread operator (...) expands an iterable (like an array) into individual elements. It is useful for copying arrays, merging arrays, and passing arguments.',
  5, ARRAY['javascript', 'es6', 'spread']),

('javascript', 'junior', 'What is event bubbling?',
  'A way to create animations',
  'When an event propagates from child to parent elements',
  'A method to sort arrays',
  'A type of async function',
  'b',
  'Event bubbling is when an event starts from the innermost element and propagates up to parent elements. You can stop it using event.stopPropagation().',
  6, ARRAY['javascript', 'events', 'dom']),

('javascript', 'junior', 'What is the purpose of Promise.all()?',
  'To create a new promise',
  'To execute promises sequentially',
  'To wait for all promises to resolve',
  'To catch all promise errors',
  'c',
  'Promise.all() takes an array of promises and returns a single Promise that resolves when all input promises have resolved, or rejects if any promise rejects.',
  6, ARRAY['javascript', 'promises', 'async']),

('javascript', 'junior', 'What is the difference between null and undefined?',
  'They are the same',
  'null is intentional absence, undefined is uninitialized',
  'null is a string, undefined is a number',
  'undefined is intentional absence, null is uninitialized',
  'b',
  'null is an intentional assignment representing "no value", while undefined means a variable has been declared but not assigned a value.',
  5, ARRAY['javascript', 'types', 'primitives']),

('javascript', 'junior', 'What does Array.map() return?',
  'A new modified array',
  'The original array modified in place',
  'A string',
  'A boolean',
  'a',
  'map() creates and returns a new array with the results of calling a provided function on every element. It does not mutate the original array.',
  4, ARRAY['javascript', 'arrays', 'methods']),

('javascript', 'junior', 'What is the purpose of async/await?',
  'To make code run faster',
  'To handle asynchronous operations in a synchronous-looking manner',
  'To create loops',
  'To handle errors only',
  'b',
  'async/await is syntactic sugar for working with Promises, making asynchronous code look and behave more like synchronous code.',
  6, ARRAY['javascript', 'async', 'promises']),

-- React Advanced (8)
('react', 'junior', 'What is the purpose of useEffect in React?',
  'To create state',
  'To perform side effects in functional components',
  'To create components',
  'To handle routing',
  'b',
  'useEffect is a Hook that lets you perform side effects in functional components, like data fetching, subscriptions, or manually changing the DOM.',
  5, ARRAY['react', 'hooks', 'useEffect']),

('react', 'junior', 'What is prop drilling in React?',
  'A debugging technique',
  'Passing props through multiple levels of components',
  'A performance optimization',
  'A testing method',
  'b',
  'Prop drilling is when you pass data from a parent component through multiple intermediate components to reach a deeply nested child component.',
  5, ARRAY['react', 'props', 'patterns']),

('react', 'junior', 'What is the purpose of React.memo()?',
  'To create memoized state',
  'To prevent unnecessary re-renders of functional components',
  'To cache API responses',
  'To handle memory management',
  'b',
  'React.memo is a higher order component that memoizes a component, preventing re-renders when props have not changed.',
  6, ARRAY['react', 'performance', 'optimization']),

('react', 'junior', 'What is the difference between controlled and uncontrolled components?',
  'Controlled components store form data in component state, uncontrolled use refs',
  'Controlled components are faster',
  'Uncontrolled components are more secure',
  'They are the same',
  'a',
  'Controlled components have their value controlled by React state (via value and onChange props), while uncontrolled components store their own state in the DOM.',
  6, ARRAY['react', 'forms', 'components']),

('react', 'junior', 'What is the Context API used for?',
  'Creating databases',
  'Managing global state without prop drilling',
  'Handling HTTP requests',
  'Styling components',
  'b',
  'Context API allows you to share values between components without explicitly passing props through every level of the component tree.',
  6, ARRAY['react', 'context', 'state-management']),

('react', 'junior', 'What does useCallback do?',
  'Creates a callback function',
  'Memoizes a callback function to prevent recreation on every render',
  'Calls a function automatically',
  'Handles errors in callbacks',
  'b',
  'useCallback returns a memoized version of the callback function that only changes if dependencies change, useful for preventing child component re-renders.',
  7, ARRAY['react', 'hooks', 'performance']),

('react', 'junior', 'What is the purpose of the key prop in lists?',
  'For styling',
  'To help React identify which items changed, added, or removed',
  'For security',
  'For accessibility',
  'b',
  'Keys help React identify which items in a list have changed. They should be stable, unique identifiers (not array indexes for dynamic lists).',
  5, ARRAY['react', 'lists', 'keys']),

('react', 'junior', 'What is lazy loading in React?',
  'Loading components slowly',
  'Code-splitting and loading components only when needed',
  'Delaying API calls',
  'A type of animation',
  'b',
  'React.lazy() enables code-splitting by allowing you to render a dynamic import as a regular component, loading it only when it is needed.',
  6, ARRAY['react', 'performance', 'code-splitting']),

-- Node.js (5)
('nodejs', 'junior', 'What is Express.js?',
  'A database',
  'A minimal and flexible Node.js web application framework',
  'A frontend framework',
  'A testing library',
  'b',
  'Express is a fast, unopinionated, minimal web framework for Node.js, used to build web applications and APIs.',
  4, ARRAY['nodejs', 'express', 'frameworks']),

('nodejs', 'junior', 'What is middleware in Express?',
  'A database layer',
  'Functions that have access to request and response objects',
  'A type of routing',
  'A security feature',
  'b',
  'Middleware functions are functions that execute during the request-response cycle, having access to req, res, and next() function.',
  6, ARRAY['nodejs', 'express', 'middleware']),

('nodejs', 'junior', 'What is the purpose of the "next()" function in Express middleware?',
  'To skip to the next route',
  'To pass control to the next middleware function',
  'To end the response',
  'To create a new request',
  'b',
  'The next() function passes control to the next middleware function in the stack. If not called, the request will be left hanging.',
  5, ARRAY['nodejs', 'express', 'middleware']),

('nodejs', 'junior', 'What is the difference between require() and import?',
  'require is CommonJS, import is ES6 modules',
  'They are the same',
  'import is older',
  'require is faster',
  'a',
  'require() is the CommonJS module syntax (Node.js), while import is the ES6 module syntax. Modern Node.js supports both.',
  5, ARRAY['nodejs', 'modules', 'syntax']),

('nodejs', 'junior', 'What is the purpose of environment variables in Node.js?',
  'To style the application',
  'To store configuration and sensitive data outside the code',
  'To create databases',
  'To handle routing',
  'b',
  'Environment variables store configuration values and sensitive data (API keys, database URLs) outside the codebase, typically in .env files.',
  5, ARRAY['nodejs', 'config', 'security']),

-- APIs (4)
('apis', 'junior', 'What is the difference between PUT and PATCH HTTP methods?',
  'PUT replaces entire resource, PATCH updates parts of it',
  'They are the same',
  'PATCH is faster',
  'PUT is for creating, PATCH is for deleting',
  'a',
  'PUT replaces the entire resource with the new data, while PATCH applies partial modifications to a resource.',
  6, ARRAY['apis', 'http', 'methods']),

('apis', 'junior', 'What is CORS?',
  'A database type',
  'Cross-Origin Resource Sharing - security feature',
  'A JavaScript framework',
  'A type of authentication',
  'b',
  'CORS is a security mechanism that allows or restricts web applications running at one origin to access resources from a different origin.',
  6, ARRAY['apis', 'security', 'cors']),

('apis', 'junior', 'What does the HTTP status code 401 mean?',
  'OK',
  'Not Found',
  'Unauthorized - authentication required',
  'Server Error',
  'c',
  '401 Unauthorized indicates that the request requires authentication and the client failed to provide valid credentials.',
  5, ARRAY['apis', 'http', 'status-codes']),

('apis', 'junior', 'What is the purpose of API authentication tokens?',
  'To speed up requests',
  'To verify the identity of the client making the request',
  'To compress data',
  'To style responses',
  'b',
  'Authentication tokens (like JWT) verify the identity of the client, allowing the server to know who is making the request and what they are allowed to do.',
  6, ARRAY['apis', 'authentication', 'security']),

-- Databases (3)
('databases', 'junior', 'What is the difference between SQL and NoSQL databases?',
  'SQL is relational with schema, NoSQL is non-relational and schema-less',
  'They are the same',
  'NoSQL is always faster',
  'SQL cannot scale',
  'a',
  'SQL databases are relational with predefined schemas (like PostgreSQL, MySQL), while NoSQL databases are non-relational with flexible schemas (like MongoDB, Redis).',
  6, ARRAY['databases', 'sql', 'nosql']),

('databases', 'junior', 'What is an index in a database?',
  'A list of tables',
  'A data structure that improves query performance',
  'A type of join',
  'A backup file',
  'b',
  'An index is a data structure that improves the speed of data retrieval operations on a database table, at the cost of additional storage and slower writes.',
  6, ARRAY['databases', 'indexing', 'performance']),

('databases', 'junior', 'What is a JOIN in SQL?',
  'A way to combine rows from two or more tables',
  'A way to delete data',
  'A type of index',
  'A backup operation',
  'a',
  'JOIN is used to combine rows from two or more tables based on a related column. Types include INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL JOIN.',
  5, ARRAY['databases', 'sql', 'joins']),

-- Security (2)
('security', 'junior', 'What is XSS (Cross-Site Scripting)?',
  'A performance optimization',
  'A security vulnerability where attackers inject malicious scripts',
  'A type of database',
  'A routing method',
  'b',
  'XSS is a security vulnerability that allows attackers to inject malicious scripts into web pages viewed by other users.',
  7, ARRAY['security', 'xss', 'vulnerabilities']);

-- =====================================================
-- SENIOR LEVEL QUESTIONS (30)
-- =====================================================

INSERT INTO interview_mcq_questions (category, experience_level, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, difficulty_score, tags) VALUES

-- React Advanced (8)
('react', 'senior', 'What are React Server Components?',
  'Components that run only on the server',
  'Components that can be rendered on the server and sent as static HTML',
  'Components for backend development',
  'A type of class component',
  'b',
  'React Server Components allow rendering components on the server, reducing JavaScript bundle size and improving initial load performance.',
  8, ARRAY['react', 'server-components', 'advanced']),

('react', 'senior', 'What is the purpose of useMemo and when should you use it?',
  'To create state',
  'To memoize expensive computations and prevent recalculation on every render',
  'To handle side effects',
  'To create context',
  'b',
  'useMemo memoizes the result of an expensive computation, recalculating only when dependencies change. Use it for computationally expensive operations or to maintain referential equality.',
  7, ARRAY['react', 'hooks', 'performance']),

('react', 'senior', 'What is the difference between useEffect and useLayoutEffect?',
  'They are the same',
  'useLayoutEffect fires synchronously before browser paint, useEffect fires after',
  'useEffect is faster',
  'useLayoutEffect is deprecated',
  'b',
  'useLayoutEffect fires synchronously after DOM mutations but before the browser paints, while useEffect fires after paint. Use useLayoutEffect when you need to measure DOM or prevent visual flicker.',
  8, ARRAY['react', 'hooks', 'lifecycle']),

('react', 'senior', 'How do you optimize a large list rendering in React?',
  'Use more state',
  'Use virtualization (react-window or react-virtualized)',
  'Use only class components',
  'Avoid using keys',
  'b',
  'Virtualization libraries render only visible items in a list, dramatically improving performance for large datasets by reducing DOM nodes.',
  7, ARRAY['react', 'performance', 'optimization']),

('react', 'senior', 'What is the purpose of Error Boundaries in React?',
  'To create errors',
  'To catch JavaScript errors in component tree and display fallback UI',
  'To handle API errors',
  'To validate props',
  'b',
  'Error Boundaries are React components that catch JavaScript errors in their child component tree, log errors, and display a fallback UI instead of crashing.',
  7, ARRAY['react', 'error-handling', 'boundaries']),

('react', 'senior', 'What is the difference between Suspense and Error Boundaries?',
  'They are the same',
  'Suspense handles loading states, Error Boundaries handle errors',
  'Suspense is deprecated',
  'Error Boundaries handle loading only',
  'b',
  'Suspense handles asynchronous loading states (showing fallback while loading), while Error Boundaries catch and handle runtime errors in components.',
  8, ARRAY['react', 'suspense', 'error-handling']),

('react', 'senior', 'What is code splitting and how do you implement it in React?',
  'Splitting code into multiple files',
  'Dynamic imports with React.lazy() and Suspense',
  'Using multiple components',
  'Splitting CSS files',
  'b',
  'Code splitting breaks your bundle into smaller chunks that can be loaded on demand using React.lazy() for components and Suspense for loading states.',
  7, ARRAY['react', 'code-splitting', 'performance']),

('react', 'senior', 'What is reconciliation in React?',
  'The process of comparing virtual DOM with real DOM',
  'The algorithm React uses to diff and update the DOM efficiently',
  'A way to merge components',
  'A state management pattern',
  'b',
  'Reconciliation is React''s algorithm for comparing the previous and current virtual DOM trees to determine the minimal set of changes needed to update the real DOM.',
  8, ARRAY['react', 'reconciliation', 'internals']),

-- JavaScript Advanced (7)
('javascript', 'senior', 'What is the event loop in JavaScript?',
  'A way to create loops',
  'The mechanism that handles asynchronous operations by managing the call stack and callback queue',
  'A type of array iteration',
  'A debugging tool',
  'b',
  'The event loop is the mechanism that allows JavaScript to perform non-blocking operations by offloading operations to the system kernel and handling callbacks.',
  9, ARRAY['javascript', 'event-loop', 'async']),

('javascript', 'senior', 'What is the difference between microtasks and macrotasks?',
  'They are the same',
  'Microtasks (Promises) execute before macrotasks (setTimeout)',
  'Macrotasks are faster',
  'Microtasks are deprecated',
  'b',
  'Microtasks (Promise callbacks, queueMicrotask) have higher priority and execute before macrotasks (setTimeout, setInterval) in the event loop.',
  9, ARRAY['javascript', 'event-loop', 'tasks']),

('javascript', 'senior', 'What is a WeakMap and when would you use it?',
  'A map with weak encryption',
  'A map with weakly-held key references that allows garbage collection',
  'A smaller version of Map',
  'A deprecated feature',
  'b',
  'WeakMap holds weak references to keys, allowing them to be garbage collected if there are no other references. Useful for associating metadata with objects without preventing garbage collection.',
  8, ARRAY['javascript', 'weakmap', 'memory']),

('javascript', 'senior', 'What is the purpose of Proxy in JavaScript?',
  'To proxy API calls',
  'To intercept and customize operations on objects (get, set, etc.)',
  'To hide code',
  'To compress data',
  'b',
  'Proxy allows you to create a wrapper for an object and intercept fundamental operations like property access, assignment, function invocation, etc.',
  9, ARRAY['javascript', 'proxy', 'metaprogramming']),

('javascript', 'senior', 'What is the difference between debouncing and throttling?',
  'They are the same',
  'Debouncing delays execution until after calls stop, throttling limits execution rate',
  'Throttling is faster',
  'Debouncing is deprecated',
  'b',
  'Debouncing delays function execution until after a period of inactivity (e.g., search input), while throttling limits how often a function can execute (e.g., scroll handler).',
  7, ARRAY['javascript', 'performance', 'optimization']),

('javascript', 'senior', 'What is the purpose of Object.freeze()?',
  'To stop code execution',
  'To make an object immutable (prevent additions, deletions, modifications)',
  'To improve performance',
  'To clone objects',
  'b',
  'Object.freeze() makes an object immutable by preventing new properties from being added, existing properties from being removed or changed, and the prototype from being changed.',
  7, ARRAY['javascript', 'objects', 'immutability']),

('javascript', 'senior', 'What is tail call optimization?',
  'Optimizing the end of functions',
  'Compiler optimization for recursive functions in tail position',
  'A way to optimize loops',
  'A debugging technique',
  'b',
  'Tail call optimization allows recursive functions in tail position to reuse the same stack frame, preventing stack overflow for deep recursion.',
  9, ARRAY['javascript', 'recursion', 'optimization']),

-- Node.js Advanced (5)
('nodejs', 'senior', 'What is clustering in Node.js?',
  'Grouping databases',
  'Spawning multiple Node.js processes to utilize multi-core systems',
  'A type of load balancer',
  'A caching strategy',
  'b',
  'The cluster module allows you to create child processes (workers) that share the same server port, enabling load distribution across CPU cores.',
  8, ARRAY['nodejs', 'clustering', 'scalability']),

('nodejs', 'senior', 'What is the difference between process.nextTick() and setImmediate()?',
  'They are the same',
  'nextTick() executes before I/O, setImmediate() executes after',
  'setImmediate is faster',
  'nextTick is deprecated',
  'b',
  'process.nextTick() executes callbacks before the next event loop iteration (before I/O), while setImmediate() executes after I/O events in the current iteration.',
  9, ARRAY['nodejs', 'event-loop', 'async']),

('nodejs', 'senior', 'What is the purpose of streams in Node.js?',
  'To style output',
  'To handle reading/writing data in chunks efficiently',
  'To create animations',
  'To manage databases',
  'b',
  'Streams allow processing data piece by piece without loading everything into memory, crucial for handling large files or real-time data.',
  8, ARRAY['nodejs', 'streams', 'performance']),

('nodejs', 'senior', 'What is the N+1 query problem and how do you solve it?',
  'A math problem',
  'Multiple database queries in a loop, solved with joins or eager loading',
  'A type of error',
  'A security issue',
  'b',
  'N+1 occurs when you make one query to fetch items, then N additional queries for related data. Solve with JOIN queries or ORM eager loading.',
  8, ARRAY['nodejs', 'databases', 'performance']),

('nodejs', 'senior', 'What is the purpose of worker threads in Node.js?',
  'To manage UI',
  'To run JavaScript in parallel threads for CPU-intensive tasks',
  'To handle routing',
  'To create clusters',
  'b',
  'Worker threads allow running JavaScript operations in parallel on separate threads, useful for CPU-intensive tasks without blocking the main event loop.',
  8, ARRAY['nodejs', 'workers', 'performance']),

-- System Design (5)
('system_design', 'senior', 'What is horizontal scaling vs vertical scaling?',
  'Horizontal adds more servers, vertical adds more power to existing server',
  'They are the same',
  'Vertical is always better',
  'Horizontal is for databases only',
  'a',
  'Horizontal scaling (scale out) adds more machines to handle load, while vertical scaling (scale up) adds more resources (CPU, RAM) to existing machines.',
  7, ARRAY['system-design', 'scaling', 'architecture']),

('system_design', 'senior', 'What is a CDN and why is it important?',
  'A type of database',
  'Content Delivery Network that distributes content geographically for better performance',
  'A security tool',
  'A programming language',
  'b',
  'CDN is a geographically distributed network of servers that delivers content to users from the nearest location, reducing latency and improving load times.',
  6, ARRAY['system-design', 'cdn', 'performance']),

('system_design', 'senior', 'What is eventual consistency in distributed systems?',
  'Data is always consistent',
  'Data becomes consistent over time, not immediately',
  'A type of database',
  'An error state',
  'b',
  'Eventual consistency is a consistency model where updates to distributed data will eventually propagate to all nodes, but may not be immediately consistent.',
  8, ARRAY['system-design', 'distributed', 'consistency']),

('system_design', 'senior', 'What is the CAP theorem?',
  'A caching principle',
  'In distributed systems, you can have only 2 of: Consistency, Availability, Partition tolerance',
  'A testing framework',
  'A security model',
  'b',
  'CAP theorem states that a distributed system can only guarantee 2 out of 3: Consistency (all nodes see same data), Availability (requests always get response), Partition tolerance (system works despite network failures).',
  9, ARRAY['system-design', 'cap', 'distributed']),

('system_design', 'senior', 'What is database sharding?',
  'Backing up data',
  'Horizontally partitioning data across multiple databases',
  'Encrypting data',
  'Compressing data',
  'b',
  'Sharding is a database architecture pattern that splits data across multiple databases/servers based on a shard key, enabling horizontal scaling.',
  8, ARRAY['system-design', 'databases', 'sharding']),

-- Security (3)
('security', 'senior', 'What is SQL Injection and how do you prevent it?',
  'A database feature',
  'An attack where malicious SQL is injected, prevented with parameterized queries',
  'A type of query',
  'A performance optimization',
  'b',
  'SQL Injection is an attack where attackers inject malicious SQL code. Prevent it using parameterized queries/prepared statements, never concatenating user input into SQL.',
  8, ARRAY['security', 'sql-injection', 'vulnerabilities']),

('security', 'senior', 'What is CSRF (Cross-Site Request Forgery)?',
  'A database attack',
  'An attack that tricks users into executing unwanted actions',
  'A type of encryption',
  'A performance issue',
  'b',
  'CSRF tricks authenticated users into executing unwanted actions on a web application. Prevent with CSRF tokens, SameSite cookies, and checking Origin/Referer headers.',
  8, ARRAY['security', 'csrf', 'vulnerabilities']),

('security', 'senior', 'What is JWT (JSON Web Token) and when should you use it?',
  'A database format',
  'A compact, self-contained token for securely transmitting information',
  'A testing tool',
  'A routing method',
  'b',
  'JWT is a compact, URL-safe token containing encoded JSON claims, commonly used for authentication and information exchange. Use for stateless authentication in APIs.',
  7, ARRAY['security', 'jwt', 'authentication']),

-- Performance (2)
('performance', 'senior', 'What is the difference between SSR and SSG?',
  'They are the same',
  'SSR renders on each request, SSG renders at build time',
  'SSG is slower',
  'SSR is deprecated',
  'b',
  'Server-Side Rendering (SSR) generates HTML on each request, while Static Site Generation (SSG) pre-renders pages at build time. SSG is faster but less dynamic.',
  7, ARRAY['performance', 'rendering', 'nextjs']),

('performance', 'senior', 'What is tree shaking in JavaScript?',
  'Removing unused code from bundles',
  'Optimizing DOM trees',
  'A type of testing',
  'A sorting algorithm',
  'a',
  'Tree shaking is a dead code elimination technique that removes unused code from JavaScript bundles, reducing file size. Works with ES6 module syntax.',
  7, ARRAY['performance', 'bundling', 'optimization']);

-- =====================================================
-- SEED COMPLETE
-- =====================================================

COMMENT ON TABLE interview_mcq_questions IS 'Seeded with 90 market-relevant MCQ questions: 30 Fresher, 30 Junior, 30 Senior';
